### PR TITLE
Extended functionality of e_facet

### PR DESCRIPTION
**Pull request by robert-koetsier**
I've added support for "pie" chart types, which require a different method to set up facets. I've added some additional arguments to the function for flexibility and user convenience. Dimensions of the grid are now determined automatically by default. Furthermore, I've completed documentation of the function's arguments.

### CODE REVIEW

**Comment by munoztd0** [comment]
thanks !

**Comment by antoine4ucsd** [comment]
Hello
I really enjoyed your set of tools. Just one quick question regarding e_facet: can you assist with the facet name/label (equivalent to strip_text in ggplot)
for now, my facet has no headers so this is hard to track it...

```
data|>
        dplyr::mutate(Label = paste0(n,"/",total))|>
        dplyr::arrange(Survey)|>
        group_by(Survey)|>
        e_chart(value)|>
        e_pie(n, 
              bind = Label,
              label = list(
                      show = TRUE,
                      formatter = "{b}",
                      position = "outside"
              )
        ) |>
        e_legend(show=T)|>
        e_tooltip(trigger = "axis", backgroundColor = "rgba(255,255,255,0.7)")|>
        e_title("Respondents per survey") |>  # Add title & subtitle
        e_theme("infographic") |>  
        e_grid(left = "20%", bottom = "60",top="60",right="10%")|>
        e_toolbox_feature(feature = c("saveAsImage"))|>
        e_facet(rows = 1, cols=4, legend_pos = "top", legend_space = 12) 
        
```

but not labels/title
Screen Shot 2024-02-12 at 10 05 45 AM
s at the top

**Comment by munoztd0** [comment]
please provide a reproducible example with dummy data

**Comment by antoine4ucsd** [comment]
good point
Here's a concrete example
```
df=data.frame(Survey=c("A","A","A","B","C","D"),
              Country=c("India","Ethiopia","Argentina","India","France","Spain"),
              n=c(1,3,1,4,1,2))



df|>
        dplyr::mutate(Label = n)|>
        dplyr::arrange(Survey)|>
        group_by(Survey)|>
        e_chart(Country,name=c("A","B","C","D"))|>
        e_pie(n,
              bind = Label,
              label = list(
                      show = TRUE,
                      formatter = "{b}",
                      position = "outside"
              )
        ) |>
        e_legend(show=T)|>
        e_tooltip(trigger = "axis", backgroundColor = "rgba(255,255,255,0.7)")|>
        e_title("Respondents per survey") |>  # Add title & subtitle
        e_theme("infographic") |>
        e_grid(left = "20%", bottom = "60",top="60",right="10%")|>
        e_toolbox_feature(feature = c("saveAsImage"))|>
        e_facet(rows = 2, cols=2, legend_pos = "top", legend_space = 12)

```

I expect something like below with label in each pie chart (n of country + relative %) and also A, B,C, D at the top of each facet
if we can adjust/reduce the space between pies. that would be even better

thank you!

Screen Shot 2024-02-12 at 11 51 12 AM

**Comment by munoztd0** [comment]
something like that ?
``` r
library(echarts4r)
library(dplyr)

df <- data.frame(Survey=c("A","A","A","B","C","D"),
              Country=c("India","Ethiopia","Argentina","India","France","Spain"),
              n=c(1,3,1,4,1,2))


splitted <- df |> group_split(Survey)


new_row <- data.frame(Survey=c("A", "A"), Country=c("France", "Spain"), n=c(NaN,NaN))
splitted[[1]] <- rbind(splitted[[1]], new_row)

create_chart <- function(data, group, color){
  data |>
    e_charts(Country) |> 
    e_pie(n, name = group) |> 
    e_color(color) |>
    e_legend(show=T, orient = 'horizontal', left = 85, top = 35)|>
    e_title(group)  |>
    e_labels(show = TRUE,
             formatter = "{b} \n {d}%",
             position = "inside") |>
    e_group("4charts") |># all charts in the same group   # Add title & subtitle
    e_theme("infographic")
}



e4 <- create_chart(splitted[[1]],  "A", c("#2ecc71", "#3498db", "#e74c3c", "#9b59b6", "#7590b3"))
e5 <- create_chart(splitted[[2]],  "B", c("#2ecc71"))
e6 <- create_chart(splitted[[3]],  "C", c("#9b59b6"))
e7 <- create_chart(splitted[[4]],  "D", c("#7590b3")) |>
  e_connect_group("4charts")

plot <- e_arrange(e4, e5, e6, e7, rows = 2, cols = 2, title = "Respondents per survey")
```

<sup>Created on 2024-02-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

image


Anyhow, if you want to continue this conversation please open a separate ISSUE

**Comment by antoine4ucsd** [comment]
yes, that works just fine! thank you

**Pull request merged**
