### PR TITLE
Try to fix e_gauge, related to #251

### PR DESCRIPTION
**Pull request by etiennebacher**
#251 shows that `e_gauge()` doesn't work with timeline, but in fact `e_gauge()` doesn't work at all when the argument `value` is something else than numeric:
```
df <- data.frame(group=c(1,2), test=c(10,90))

df %>% e_charts() %>%
    e_gauge(test, "PERCENT")
``` 
Here, to my knowledge, it is not possible to allow for both an unquoted word and a numeric argument in `e_gauge`, because we would need to detect which type of argument it is:

* we can test whether the argument is numeric 

* we can't test whether the argument is an unquoted text because it will say "object *** not found", and we can only do `deparse(substitute(test))` if we're sure the argument is an unquoted text, etc.

So I de-deprecated `e_gauge_()` (I don't know why it was deprecated) and the argument must be a `character` (just to be consistent with the other `e_*_()` functions, that take characters).

With this, we can pass a character argument to `e_gauge_()`:
```
df <- data.frame(group=c(1,2), value=c(10,90))

df %>% 
  e_charts() %>%
  e_gauge_("value", "PERCENT")
```
but there's still a problem with the timeline:
```
df <- data.frame(group=c(1,2), value=c(10,90))

df %>% 
  group_by(group) %>%
  e_charts(timeline=TRUE) %>%
  e_gauge_("value", "PERCENT")
```
The number change as expected, but there is some overlapping with a big `NaN`. I'm not sure if I'll have the time to work on this soon so I just put this here, maybe somebody will build on this.

### CODE REVIEW

**Comment by rdatasculptor** [comment]
Thank you for the quick response and your efforts to fix it!
Maybe you can change `name[i]` into `name`, because when i > 1, the name part is empty. 
I will try to deal with the big `Nan`. Maybe I can find a solution for that one.

**Comment by JohnCoene** [comment]
I really cannot find out where this NaN comes from, it's baffling...

**Comment by rdatasculptor** [comment]
Yes, and the strange thing is, if you set timeline to FALSE, the NaN is gone and the values shown are as expected. 
Could it be related to the empty name[i] if i > 1...?

**Comment by swsoyee** [comment]
It's seems not relate to the `name`, but I think it probably relate to the data structure in options, but I can't fix it, so I just leave my search result here.

In the Echarts docs, https://echarts.apache.org/examples/en/editor.html?c=gauge, the original code is
```js
option = {
    tooltip: {
        formatter: '{a} <br/>{b} : {c}%'
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter: '{value}%'},
            data: [{value: 50, name: '完成率'}]
        }
    ]
};

setInterval(function () {
    option.series[0].data[0].value = (Math.random() * 100).toFixed(2) - 0;
    myChart.setOption(option, true);
},2000);
```
the `data[0].value` is reset by time.

But with timeline in `echarts4r`, the data structure is something like (not pretty sure)
```js
data: [{value:10, name: 'PERCENT'}, {value:90, name: 'PERCENT'}]
```

If you change the original code in Echarts sample to
```js
option = {
    tooltip: {
        formatter: '{a} <br/>{b} : {c}%'
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            name: '业务指标',
            type: 'gauge',
            detail: {formatter: '{value}%'},
            data: [{value: 10, name: '完成率'}]
        },
        {
            name: '业务指标',
            type: 'gauge',
            data: [{value: undefined}]
        }
    ]
};

setInterval(function () {
    // option.series[0].data[0].value = (Math.random() * 100).toFixed(2) - 0;
    myChart.setOption(option, true);
},2000);
```
You can reproduce the `NaN`, so I think the reason may relate to the incorrect data structure when using `timeline` option, but I'm not pretty sure about it and can  not fix it too.

**Comment by etiennebacher** [comment]
Got it! There was just a `list()` that wasn't needed (thanks @swsoyee for the hint on the structure)

**Comment by rdatasculptor** [comment]
brilliant work guys! thanks!

**Pull request merged**
